version: '3'
services:
  db:
    image: postgres
    container_name: matchy-matchy-db
    environment:
      POSTGRES_USER: moha
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: matchy-matchy-db
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: matchy-matchy-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: